### ISSUE TITLE
SocketException on publish with forceKick=true while reconnecting

### ISSUE THREAD

**Issue by film42** [nats-io/java-nats#105]
Looks like when you call publish with force flush, the "kick the flusher" is not protected with a try/catch and ends up raising a `SocketException` error to the caller. Is this behavior considered correct or incorrect? Seems like a bug to me, but I was just wondering what you guys thought.

I found this while testing failover scenarios where I have two gnatsd servers in a cluster with only one running.

1. I connect java-nats to the running gnatsd server.
2. I begin sending publish in a loop.
3. I start the second gnatsd server and stop the first server.
4. A `SocketException` is raised to the caller where I expected no error to be raised.

The offending code seems to be here: https://github.com/nats-io/java-nats/blob/b320df5d551d6df7d8f445c368218fe737f126b4/src/main/java/io/nats/client/ConnectionImpl.java#L2006-L2009. We are attempting to flush the socket's output stream when the socket is closed.

**Comment by ColinSullivan1** [comment]
That definitely looks like a bug; thank you for raising this issue.
