### ISSUE TITLE
Add handler invoked when a new server joins the NATS Cluster

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/java-nats#116]
Add functionality to mirror the go-nats feature, nats-io/go-nats#282.

**Comment by sasbury** [comment]
We are working on a new version of the client that will resolve this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch.

**Comment by sasbury** [comment]
Version 2 is released and has this callback in the ConnectionListener as the DISCOVERED_SERVERS event.
