### ISSUE TITLE
Add compilation and tests for documentation examples

### ISSUE THREAD

**Issue by petemiron** [nats-io/java-nats#121]
Test added to private repo for basic usage: https://github.com/nats-io/java-nats-examples/blob/master/src/test/java/io/nats/jnats/AppTest.java

We need to add tests for:

- [ ] TLS
- [ ] Wildcard Subscriptions
- [ ] Queue Groups
- [ ] Advanced Usage
- [ ] Clustered Usage

**Comment by sasbury** [comment]
Obsolete for 2.0, all examples are now from the examples folder.
