### ISSUE TITLE
Build Error on windows

### ISSUE THREAD

**Issue by roli8200** [nats-io/java-nats#123]
Cannot build java nats on windows:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (prepare) on project jnats: An Ant BuildException has occured: **Can't get https://github.com/nats-io/g
natsd/releases/download/v0.9.4/gnatsd-v0.9.4-windows-${nats.arch}.zip to D:\EclipseWorkspace\HouseControlCommunication\jnats\java-nats-0.5.3\target\gnatsd-v0.9.4-windows-${nats.arch}.zi**
p
[ERROR] around Ant part ...<get skipexisting="true" src="https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-windows-${nats.arch}.zip" dest="D:\EclipseWorkspace\Hou
seControlCommunication\jnats\java-nats-0.5.3\target" unless:true="${server.installed}"/>... @ 9:249 in D:\EclipseWorkspace\HouseControlCommunication\jnats\java-nats-0.5.3\target\antrun\
build-copy-server-exec.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by ColinSullivan1** [comment]
@roli8200 , We appreciate your interest in NATS!

I was able to reproduce this error; thank you for raising this issue.

The workaround is to:

* Create an empty file named `gnatsd` inside the `java-nats/target` directory to prevent the download attempt.  The basic tests run by `mvn install` should pass for you at this point.
* If you are developing additional tests or will be running integration tests, you'll want to install `gnatsd` manually (you can download it from the [release](https://github.com/nats-io/gnatsd/releases/tag/v1.0.2), or through chocolatey `choco install gnatsd`).  `gnatsd`must be in your path.


We'll be working on a fix in the meantime.
