### ISSUE TITLE
How to set durable subscription ? 

### ISSUE THREAD

**Issue by shaiaTradair** [nats-io/java-nats#124]
How to set durable subscription ?
Can't find method that handle it ? 

public SyncSubscription subscribe(String subject) {
        return this.subscribeSync(subject, (String)null);
    }

    public SyncSubscription subscribe(String subject, String queue) {
        return this.subscribeSync(subject, queue);
    }

    public AsyncSubscription subscribe(String subject, MessageHandler cb) {
        return this.subscribe(subject, (String)null, cb);
    }

    public AsyncSubscription subscribe(String subj, String queue, MessageHandler cb) {
        return (AsyncSubscriptionImpl)this.subscribe(subj, queue, cb, (BlockingQueue)null);
    }

  public SyncSubscription subscribeSync(String subject, String queue) {
        return (SyncSubscription)this.subscribe(subject, queue, (MessageHandler)null, this.createMsgChannel());
    }

    public SyncSubscription subscribeSync(String subject) {
        return (SyncSubscription)this.subscribe(subject, (String)null, (MessageHandler)null, this.createMsgChannel());
    }

**Comment by ColinSullivan1** [comment]
@shaiaTradair , Thank you for your interest in NATS!

This client is for use with core NATS; durable subscriptions are a feature of NATS streaming.  You can find more information related to durable subscribers [here](https://github.com/nats-io/java-nats-streaming#durable-subscriptions), in the java-nats-streaming client.
