### ISSUE TITLE
Make Subscription isValid check more robust

### ISSUE THREAD

**Issue by stevenosborne-wf** [nats-io/java-nats#126]
The documentation for a `Subsriptions`'s `isValid` method claims to check if subscription is "active". However, looking over the source code, it appears to just check that the `Subscription` object was initialized with a non-null [`ConnectionImpl`](https://github.com/nats-io/java-nats/blob/1.0/src/main/java/io/nats/client/SubscriptionImpl.java#L73). This private `conn` class variable doesn't even to be set to `null` upon [`unsubscribe`](https://github.com/nats-io/java-nats/blob/1.0/src/main/java/io/nats/client/SubscriptionImpl.java#L125-L142). As a minimum, `conn` should be set to `null` on `unsubscribe`. Ideally, it would check more state on the connection to ensure messages can actually make it to the subscription.

**Comment by tylertreat** [comment]
It looks like the subscription's `conn` is already being set to `null`: https://github.com/nats-io/java-nats/blob/1.0/src/main/java/io/nats/client/ConnectionImpl.java#L1527-L1528

**Comment by sasbury** [comment]
We are working on a new version of the client that should resolve this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch. Feedback is appreciated.

**Comment by sasbury** [comment]
Fixed in version 2.
