### ISSUE TITLE
[Documentation] Add more detailed explanations and examples of the driver features

### ISSUE THREAD

**Issue by jebbench** [nats-io/java-nats#127]
I've found the following to be missing from the documentation:

- A link to the streaming driver/note that this ISN'T the streaming driver.
- The different ways to connect - e.g. the different connection types and how to use the ConnectionFactory for each of them.

Adding a wiki giving more detail on the above would be helpful.

**Comment by ColinSullivan1** [comment]
@jebbench , thank you for raising this issue.  We do need to update the documentation and make a clearer distinction between NATS and NATS streaming.

**Comment by sasbury** [comment]
We are updating the documentation on the main site. The JavaDoc for the client library also has new doc. I will leave this open until we release the new website.

**Comment by sasbury** [comment]
Take a look at the new doc and feel free to let us know if we need more.
