### ISSUE TITLE
Client stops reconnecting after a reconnect failure

### ISSUE THREAD

**Issue by bagguley** [nats-io/java-nats#128]
I'm using Nats streaming 0.5.0 but with the normal Java client version 0.7.3. There is a high data rate and recently I encountered weird behaviour. I think the server was cutting off the client because it was too slow, the connection is configured to reconnect automatically, which it did but it looks like the server disconnected the client before the doReconnect() method is finished and this results in an exception on line 1075 (version 0.7.3) and it doesn't seem to recover. Sometimes, before failing, it reconnects but I get errors indicating that the stream has become corrupt.

Ideally I would like some control around how the server decides what's a slow consumer, e.g. increasing buffer size, to smooth out temporary glitched. Failing that, I would like the server not to cut off the client moments after it has reconnected and the client handle it properly if it does happen.

**Comment by ColinSullivan1** [comment]
@bagguley , Thank you for raising this issue:  It looks like we we need to document the write deadline in the NATS server configuration.

First, about the corrupt data stream - when reconnecting, there is the possibility of a partial message in the in the client's write buffer.  This is likely what you are seeing.  If this happens, your client will discarded the partial message and reconnect to another server. 

If you increase the `write_deadline` in your server configuration, you can reduce the chance of getting slow consumer errors by allowing more messages to buffer in server before a consumer is considered slow.  An example configuration using the write deadline can be found [here](https://github.com/nats-io/gnatsd/blob/v1.0.2/server/configs/test.conf#L42).  You may want to experiment with values of `5s` or even `10s`. Bear in mind, buffering in the server is not always the best approach - if this ends up being a persistent problem you may want to consider scaling with queue groups or metering your publishing application.
