### ISSUE TITLE
Allow to disable reconnecting buffer

### ISSUE THREAD

**Issue by avlasor** [nats-io/java-nats#138]
Hi! 
I would like to propose to allow the disabling of reconnecting buffer. Currently in Go client it can be done setting the buffer size with -1 but for java client it is not possible. If we set buffer size  to -1 or 0, the default value for buffer is taken. Moreover if a small size is configured (for example 1), the first message is always buffered and resend when client is reconnect. I was asking about it in the google group (https://groups.google.com/forum/#!topic/natsio/UZJmWqpSc9E). 

Would it be possible to implement this behavior?  I think that it would be useful in cases in which the messages are in real time and an old message could produce to get wrong information.

Regards
Rosalva

**Comment by sasbury** [comment]
We are working on a new version of the client that should resolve this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch. Feedback is appreciated.

**Comment by avlasor** [comment]
Hi!I am on holidays. As soon as I start to work I'll try it. Thank you very much

**Comment by sasbury** [comment]
Released 2.0.0, you can now use -1 to get this behavior.
