### ISSUE TITLE
Subscription dies when an unchecked exception is thrown in the message handler

### ISSUE THREAD

**Issue by RedShift1** [nats-io/java-nats#139]
Consider this code:

```
nats.subscribe(
    "someTopic",
    new MessageHandler()
        {
            @Override
            public void onMessage(Message message)
            {
                someOperation(message); // This throws an unchecked exception for some reason
            }
        }
    );
```

When someOperation(...) throws an unchecked exception, the subscription dies and no further messages are delivered to the handler.

The expected behaviour would be that the message handler keeps receiving messages.

**Comment by kozlovic** [comment]
This has been already addressed in master: https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/ConnectionImpl.java#L1406
There are plans to have a release soon.

**Comment by RedShift1** [comment]
Ah ok. I was testing this on version 1.0. Just ignoring it seems like a bad idea, although processing continues, your messages would still be disappear and you'd have no idea why. Wouldn't it be better if the exception was logged or at least t.printStackTrace()?

**Comment by kozlovic** [comment]
It's a library, so logging may not mean anything (or not be wise) depending on how the library is used. I think that ignoring user level exceptions at the library level is perfectly fine. If the user is concerned that some code he/she calls inside the message callback may throw an exception, then he/she should catch it and do appropriate actions based on the application logic.

**Comment by ColinSullivan1** [comment]
I agree with @kozlovic.  While ignoring exceptions and dropping messages can cause some confusion during development, how to handle those exceptions is entirely application dependent.

**Comment by RedShift1** [comment]
Perhapss rethrow it as a checked exception then?

**Comment by kozlovic** [comment]
Not sure what you are asking here. The issue you reported is that your message handler is not handling an exception that some code you invoke may throw. As we explained, the current code in master will ignore all exceptions thrown by the user so that dispatching of other messages continues. If you want to catch exception thrown by your code you should catch it.
