### ISSUE TITLE
subject in message is sometime truncated

### ISSUE THREAD

**Issue by MarcGuiot** [nats-io/java-nats#141]
Hi,
On Mac OS (10.13) with the version 1.0 and 1.1-Snapshot of java-nats and using the latest docker nats image, the subject of the message is sometimes truncated (at very low frequency). That is, the subject only partially match the subject the subscription was done one. Still, the message is received correctly.

Attached, you will find a java main that show the problem (after some time).

I fail to understand deeply in the parser why sometime the beginning of the subject is truncated.

Here an output:
BUG: Receive : 1a45 expected : content.path.8db98b6a-7ec2-494f-8cce-d80629911a45

[CheckNatsSubject.txt](https://github.com/nats-io/java-nats/files/1545655/CheckNatsSubject.txt)

Thanks for help,
Marc Guiot

**Comment by tylertreat** [comment]
Thanks, I will take a look at this.

**Comment by tylertreat** [comment]
@MarcGuiot How long do you normally have to run the program before hitting an error? I have not been able to reproduce on MacOS 10.13 with jnats 1.0 and Java 1.9 after running for several minutes.

**Comment by MarcGuiot** [comment]
Hi, less then a minute:
start 2017-12-12T17:21:11.598
Parser.processMsgArgs missing 14
Parser.processMsgArgs 14
Message.setSubject 14
BUG: Receive : b-666bfabbd9e1 expected : content.path.0a79c8b8-efce-4664-b47b-666bfabbd9e1
Reader.startRead 2017-12-12T17:21:40.857

JDK 1.8.0_144

**Comment by tylertreat** [comment]
I'm unable to reproduce with JDK 1.8.0_131, JDK 1.8.0_152, and JDK 9.0.1. It's entirely possible there is a race that simply isn't exposed on my machine though. @kozlovic can you try running this test?

**Comment by kozlovic** [comment]
Will try...

**Comment by kozlovic** [comment]
I am able to reproduce, sometimes, if I run the server from the docker image. May help with the timing...

**Comment by tylertreat** [comment]
I will try running with Docker. I was running it natively but missed that @MarcGuiot was running the Docker image.

**Comment by tylertreat** [comment]
I've successfully reproduced using the Docker image. Hopefully can debug now...

**Comment by MarcGuiot** [comment]
Thank you for the fix.
