### ISSUE TITLE
async request/response not possible?

### ISSUE THREAD

**Issue by santo74** [nats-io/java-nats#143]
I'm currently using an async, non-blocking java toolkit for my application so it is very important that my requests don't block. With the current implementation of java-nats I see no possibility to make async/non-blocking request/response calls. Is that correct or am I overlooking something?

In comparison to the node-nats library it seems there are several features missing in this java version.
No requestOne(), no possibility to specify request options (e.g. max=1 to auto-unsubscribe after first response has received), request method is not async, ...

I think Nats is a wonderful messaging system and that's why I want to use it in my application.
Actually I'm currently using Hazelcast, but that's too unreliable for me and therefore I want to replace it with Nats, but then I need async/non-blocking behaviour ;-)

**Comment by kozlovic** [comment]
@santo74 You can do non blocking request/reply. You simply need to set up your subscription first, then use one of the publish() method that takes either a message or a reply subject. 
As for requestOne(), this is the behavior of the default request() call. For max messages, if you setup your own subscription first, you can use auto-unsubscribe API to set to the value you want before sending the request.

**Comment by santo74** [comment]
Ok, I see now.
Still it would be nice that the different clients mirror the same features (methods), at least all the official ones.

Thanks!

**Comment by kozlovic** [comment]
Thanks for the feedback! Keep in mind that Node.js is asynchronous by nature. The requestOne() was actually recently added to provide the request() semantic of the other languages. That is, in Java, Go, etc.. request() accepts a timeout and deals with a single reply.
Even in NATS Node client, you would need to deal with timeout yourself if using the generic request() method.

**Comment by santo74** [comment]
Ok, that makes sense indeed.
I'll implement my own requestOne() method for now.

Thanks again.
