### ISSUE TITLE
[jnats] cross platform question

### ISSUE THREAD

**Issue by fadeAce** [nats-io/java-nats#144]
1.  in using NATS, I wrote two client based on java-nats & node-nats (and maybe future a golang client),it's okay when using pub/sub model to do communication , but when using request and response(RPC), can it support well at those two different platform client ?
2.  is there a support of official NATS QUEUE model?I didn't find it.

**Comment by ColinSullivan1** [comment]
@fadeAce , Thank you for your interest in NATS!  Yes, all officially supported platforms support request/reply, and communicate with each other as they all communicate over the NATS protocol.

Queues aren't supported today.  However, [durable subscriptions](https://github.com/nats-io/go-nats-streaming#durable-subscriptions) in [NATS streaming](https://nats.io/documentation/streaming/nats-streaming-intro/) will cover many of the use cases that queues will.

Can you describe your general use case and how you are using NATS?

**Comment by fadeAce** [comment]
@ColinSullivan1 ,thanks for your reply. In functional pub sub model, I can't do a point to point communication, then i have to implement it in RPC model .So there's a blocked thing to me , that is the request/response given in  Nats client api still a pub sub model but in using a unique subject modified by some kind of mechanisms. So ,will the request/response have the same latency as pub sub? If like that ,will it justlike if I find a mechanism to build a unique subject for example UUID then pub sub at this subject then will I fulfill a RPC model with the same performance api has given?

**Comment by ColinSullivan1** [comment]
@fadeAce , You are correct - NATS supports the request/reply pattern (see the `Connection.request` API), by using publish/subscribe with unique subjects.  NATS request/reply will have the same latency characteristics as publish/subscribe.  

Given NATS performance characteristics, I'd suggest you test out latency with NATS request/reply in your environment and see if latency is sufficient.  In cases where you need extremely low latency, you can use NATS to coordinate a p2p session with another protocol (http, gRPC, etc).

**Comment by fadeAce** [comment]
@ColinSullivan1 ,thanks for these details ,but , when testing unit test at gnatsd, sth went wrong:
$ go test ./test/cluster_test.go 
# command-line-arguments
test/cluster_test.go:66: undefined: RunServerWithConfig
test/cluster_test.go:67: undefined: RunServerWithConfig
test/cluster_test.go:100: undefined: createClientConn
test/cluster_test.go:103: undefined: createClientConn
test/cluster_test.go:106: undefined: setupConn
test/cluster_test.go:109: undefined: pongRe
test/cluster_test.go:115: undefined: setupConn
test/cluster_test.go:118: undefined: pongRe
test/cluster_test.go:120: undefined: expectMsgsCommand
test/cluster_test.go:123: undefined: checkMsg
and this a option is done by following gnatsd doc unit test, i mean i can see the config configures but why no detected, is it a missing option there? Thanks in advance.

**Comment by ColinSullivan1** [comment]
@fadeAce , you'll want to run the go unit tests from the test directory.

```text
$ pwd
/Users/me/go/src/github.com/nats-io/gnatsd/test
$ go test -v
=== RUN   TestNoAuthClient
--- PASS: TestNoAuthClient (0.03s)
=== RUN   TestAuthClientBadToken
--- PASS: TestAuthClientBadToken (0.03s)
```

**Comment by fadeAce** [comment]
@ColinSullivan1  when reading source code , I find two readloop are the same .

from route.go: s.start() -> if opts.Cluster.Port != 0  -> {<-clientListenReady} -> go s.routeAcceptLoop(ch) -> s.createRoute(conn, nil) ->
	// Spin up the read loop.
	s.startGoRoutine(func() { c.readLoop() })
from server.go: s.start() -> Acceptloop() -> for s.isRunning() -> s.createClient(conn) ->
	// Spin up the read loop.
	s.startGoRoutine(func() { c.readLoop() })

I find that when no cluster is up, code's into second loop, but a channel is blocked there as  **clientListenReady** .  Haven look through Acceptloop(clientListenReady), I find the only thing is to close this channel (and then set it to be nil), so I can't find a injection into this channel(that is , to unblock clientListenReady), so how it works, thanks ?

**Comment by fadeAce** [comment]
@ColinSullivan1 , after a period of deep learn into gnatsd & it's api I find that it seems with no approach to limit a subscriber,  whatever I want in sub is no restricted or that is to say only password at auth connection not at sublist, what if I want to limit a sub behavior to not all subject ,how to ? Thanks Collin.

**Comment by ColinSullivan1** [comment]
@fadeAce , I'm not sure I understand exactly what you are asking for, but it sounds like publish/subscribe permissions may help.  If you look [here](https://github.com/nats-io/gnatsd#authorization), you can find how to configure authorization to prevent publishing and subscribing to specific subjects for a particular user.  Does this help?

**Comment by fadeAce** [comment]
@ColinSullivan1 ,yes ,the scene is almost like this , but the difference is that I don't know what subject is gonna be pub and sub as a server , but client user decide it . And a client determines what subject could do sub, maybe using password when doing publish as a param and subscriber do sub to match the pwd at beginning , not a prior configure loaded in server.

**Comment by fadeAce** [comment]
@ColinSullivan1 and there is a issue seen from readMe.md that request() may failed in Linux, and I used request in windows added JVM option as the issue has recommed, but it seems no work.
And in my mac the test is passed
here is the code :
    @Test
    public void reqAndRep() throws Exception{
        Connection nc = Bus.connect();
        nc.subscribe("help", message -> {
            try {
                nc.publish(message.getReplyTo(), "I can help!".getBytes());
            } catch (Exception e) {
                e.printStackTrace();
            }
        });
        Message msg = nc.request("help", "help me".getBytes(), 50000);

        System.out.println(new String(msg.getData()));
    }
Even I give it 50 seconds , still a timeout error in windows10 .
