### ISSUE TITLE
NATS hangs after "i/o exception when flushing output stream"

### ISSUE THREAD

**Issue by RedShift1** [nats-io/java-nats#145]
While running for an extended time, the library seems to hang when trying to publish new messages after this exception occurs:

```
2018-01-05T08:45:19,489 WARN  [io.nats.client.ConnectionImpl ] couldn't connect to nats://redacted:redacted (Connection reset by peer: socket write error)
2018-01-05T08:45:21,692 WARN  [io.nats.client.ConnectionImpl ] nats: i/o exception when flushing output stream
2018-01-05T08:45:21,770 WARN  [io.nats.client.ConnectionImpl ] couldn't connect to nats://redacted:redacted (Connection reset by peer: socket write error)
2018-01-05T08:45:23,239 WARN  [io.nats.client.ConnectionImpl ] nats: i/o exception when flushing output stream
2018-01-05T08:45:23,317 WARN  [io.nats.client.ConnectionImpl ] couldn't connect to nats://redacted:redacted (Connection reset by peer: socket write error)
2018-01-05T08:45:25,302 WARN  [io.nats.client.ConnectionImpl ] nats: i/o exception when flushing output stream
```

This is the code that sends messages:

```
    @Override
    protected void run() throws IOException // Run is being executed in a thread
    {
        Connection nats = this._setupNats(this._natsUrl);

        Envelope envelope;

        while(this.isRunning())
        {
            try
            {
                envelope = this._outQueue.take();
            }
            catch (InterruptedException e)
            {
                return;
            }

            try
            {
                nats.publish(envelope.getTopic(), envelope.msgToBytes());
            }
            catch (RuntimeException | SerializationException | CompressionException ex)
            {
                ex.printStackTrace();
            }
        }
    }

    @Subscribe
    @AllowConcurrentEvents
    public void newOutMsg(Envelope envelope)
    {
        this._outQueue.add(envelope); // This method is throwing exceptions stating that the queue is full
    }

    private Connection _setupNats(String url)
    {
        RetryConfig retry = new RetryConfigBuilder()
            .retryOnAnyException()
            .withDelayBetweenTries(30, ChronoUnit.SECONDS)
            .withMaxNumberOfTries(5)
            .withExponentialBackoff()
            .build();

        Callable<Connection> callable = () ->
        {
            this._l.trace("Connecting to " + url);
            try
            {
                return Nats.connect(url, this._natsOptions);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.getMessage());
            }
        };

        CallExecutor<Connection> retryConfig = new CallExecutor<>(retry);

        CallResults<Connection> execute = null;

        boolean keepTrying = true;
        do
        {
            try
            {
                execute = retryConfig.execute(callable);
                keepTrying = false;
            }
            catch (RetriesExhaustedException ex)
            {
                this._l.warn("Retries to connect exhausted. Trying again.");
            }
        }
        while (keepTrying);

        this._l.info("Connected to " + url);

        return execute.getResult();
    }

```
The only way I can tell that the library is hanging, is because `this._outQueue.add(envelope)` keeps throwing exceptions that the outbound queue is full. No other stacktraces are emitted. I've been having this problem for a while and I was hoping that the `ex.printStackTrace()` would show anything, but alas no.

**Comment by RedShift1** [comment]
Note that `netstat` shows an active connection to the NATS server in `ESTABLISHED` state.

**Comment by kozlovic** [comment]
@RedShift1 The thread creates a connection and then publishes. Two things could go wrong: the connection is permanently lost, and all subsequent publish call will fail, or the connection reconnects, but the time of disconnect and/or the amount of publish messages while disconnected causes the reconnect buffer to be full and publish to throw an exception.

In any case, you are not catching the checked `IOException` in the try/catch code where you do the publish, but have it in `run()` so if an exception occurs, your thread will exit.
This is consistent with what you saw where the code adding to your `_outQueue` throws an exception indicating that it is full, since the "publisher" has exited and it seem this is the one dequeueing this queue.

**Comment by RedShift1** [comment]
My thread does not exit. The class running the thread extends from Guava's [AbstractExecutionThreadService](https://github.com/google/guava/wiki/ServiceExplained) and the service manager has a listener that watches for threads dying. I have tested this functionality and it definitely works, so I'm still suspecting the thread is hanging on nats.publish(). I've been trying to create a reproducible test case but so far no luck. I think the underlying connection was in some kind of half open state caused by a complete disconnect followed by partial connectivity.

**Comment by kozlovic** [comment]
Sorry about the delay. Try to capture thread dumps when this problem occurs again and we can have a look. Thanks!

**Comment by sasbury** [comment]
Also, i would be interested if you have the same issue in 2.0

**Comment by RedShift1** [comment]
Will check this out.

**Comment by sasbury** [comment]
Closing 1.x issue, let me know if it crops up in 2.x.
