### ISSUE TITLE
When reconnecting, ignorred IO errors can lead to silently broken connection

### ISSUE THREAD

**Issue by edam** [nats-io/java-nats#150]
IOExceptions thrown as a result of writing to the OutputStream during a reconnect, whilst trying to write subscription (and pending) commands are currently silently ignored. This could lead to the scenario where the library believes it has successfully recovered a connection, but where some subscriptions have not been re-established.

This scenario may also be especially likely, given that the reconnection code may run where there are networking issues/partitions . At this time, conceivably, a backlog of pending RPC-like requests (i.e., publishes that require a response via a one-shot inbox) may have accumulated, leading to an excess of subscriptions to re-establish.

**Comment by edam** [comment]
https://github.com/nats-io/java-nats/pull/149

**Comment by sasbury** [comment]
We are working on a new version of the client that should resolve this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch. Feedback is appreciated.

**Comment by sasbury** [comment]
I spent a lot of time on trying to make sure closed is closed, and reconnect is reconnect. Please take a look at 2.0 and reopen this if you are still seeing an issue.
