### ISSUE TITLE
Lots of threads in waiting state

### ISSUE THREAD

**Issue by santo74** [nats-io/java-nats#151]
In response to [this](https://github.com/nats-io/java-nats/issues/143) issue I implemented my own RequestOne() method.
Code can be found below.
However, over time (hours or days, depending on the load/activity on the server) I see an increasing number of threads on the system (thousands) finally resulting in OutOfMemory errors (Unable to create new native thread).

The threaddump contains thousands of jnats-subscriptions in WAITING state:

```
"jnats-subscriptions" #150 prio=5 os_prio=0 tid=0x00007fbf0c018000 nid=0x6095 waiting on condition [0x00007fbf64840000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000fcb25cc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at io.nats.client.ConnectionImpl.waitForMsgs(ConnectionImpl.java:1407)
        at io.nats.client.ConnectionImpl$10.run(ConnectionImpl.java:1834)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at io.nats.client.NatsThread.run(NatsThread.java:59)

   Locked ownable synchronizers:
        - <0x00000000fcb03d18> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"jnats-subscriptions" #56 prio=5 os_prio=0 tid=0x00007fbf0c01a000 nid=0x31e0 waiting on condition [0x00007fbf64e46000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000fcacdda0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at io.nats.client.ConnectionImpl.waitForMsgs(ConnectionImpl.java:1407)
        at io.nats.client.ConnectionImpl$10.run(ConnectionImpl.java:1834)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at io.nats.client.NatsThread.run(NatsThread.java:59)

   Locked ownable synchronizers:
        - <0x00000000fcacdaa8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

This is the relevant code for my RequestOne() implementation:

```
	// 1. Prepare a new reply address
	String replyAddress = nc.newInbox();
							
	// 2. Subscribe to the new reply address in order to receive any feedback from the remote service
	AsyncSubscription sub = nc.subscribe(replyAddress, reply -> {
		// reply received, cancel our timeout watcher
		cancelTimeoutWatcher(timerId(), replyAddress, address);
		
		logger.info("Call to remote service " + address + " finished successfully");

		byte[] replyData = reply.getData();
		
		...
	});
	
	// 3. Remove subscription as soon as we received a reply from (one of) the remote service(s)
	sub.autoUnsubscribe(1);
	
	// 4. Publish our request to (one of) the remote service(s)
	nc.publish(address, replyAddress, request.encode().getBytes());
	
	// 5. Specify and handle timeout
	Long watcherId = activateTimeoutWatcher(promise, sub, timeout, replyAddress, address);

			
    private Long activateTimeoutWatcher(final Future<JsonObject> promise, final AsyncSubscription sub, final Long timeout, final String localInbox, final String remoteAddress) {
        Long timerId = null;
		logger.trace("Activating timeout watcher for local subscription (" + localInbox + ") to remote address (" + remoteAddress + ")");
		
		timerId = vertx.setTimer(timeout, id -> {
			if (sub != null && sub.isValid()) {
				try {
					logger.error("Call to remote service " + remoteAddress + " timed out");
					sub.unsubscribe();
					if (!promise.isComplete()) {
						promise.fail("Service not available (timeout)");
					}
				}
				catch (IOException ioe) {
					logger.error("An unexpected error occured while removing local subscription (" + localInbox + ") for remote address (" + remoteAddress + ")");
					if (!promise.isComplete()) {
						promise.fail("Service not available (hard timeout)");
					}
				}
			}
			else {
				if (!promise.isComplete()) {
					promise.fail("Service not available (soft timeout)");
				}
			}
		});            
        
        return timerId;
    }

    private boolean cancelTimeoutWatcher(final Long timerId, final String localInbox, final String remoteAddress) {
        boolean cancelResult = Boolean.FALSE;
        if (timerId != null) {
            cancelResult = vertx.cancelTimer(timerId);
        }
        return cancelResult;
    }
```

What could be causing this? Am I doing something wrong in my code?

Thanks

**Comment by kozlovic** [comment]
By default each subscription has a thread to dispatch its message. We added an option to have a pool of threads responsible for messages dispatching. However, you may not need that if you know that the number of active subscriptions should be bounded.
Depending on which version you are using there may have been a defect that would not notify the subscription thread to exit when the subscription is unsubscribed. I believe that it should work fine from master branch, if you could try from there?

**Comment by santo74** [comment]
Ok, thanks for the pointers.
Is it [this](https://github.com/nats-io/java-nats/issues/111) issue you're referring to regarding subscription threads not being closed correctly?
This issue was fixed almost a year ago, so I expected it to be in the most recent stable version already.

But looking at the date of the current stable release, which is 1.0 as far as I can tell,  I noticed it's already over 1 year old!
Aren't there any plans to make a new release any time soon?
Subscriptions not being closed correctly, severe performance degradation (cfr [this](https://github.com/nats-io/java-nats/issues/99) issue), and possibly other issues would justify a new stable release in my opinion.

**Comment by santo74** [comment]
@kozlovic I finally managed to reproduce the issue in my dev environment with the latest stable jnats release v1.0.
It only seems to happen when there are many concurrent requests (which is obviously not the case in a dev environment).
Anyway, after I was able to reproduce the issue I updated the jnats dependency from 1.0 to the latest master and I couldn't reproduce it anymore.
Even under heavy load the number of threads remained very stable (around 500)

So it would be really appreciated if a new official release could be made that includes this fix.

**Comment by kozlovic** [comment]
Good to hear. We will discuss internally as to when we will issue a new release. I agree that it is long overdue. Thank you for your patience.

**Comment by santo74** [comment]
Ok, thanks for getting it discussed internally.
I hope you understand I'm not too keen on installing a snapshot version in my production environment ;-)

**Comment by sergeyzenchenko** [comment]
Hey guys, any news on this issue? We are having crashes in production because of it :/

**Comment by santo74** [comment]
Hi @sergeyzenchenko and @kozlovic
Yes, an official release would be really appreciated.
Because of the continuous crashes in production I had no choice but start using the snapshot version in production.
I really don't like the idea of running a snapshot in production, but at least I didn't have any crashes anymore.

So please make an official release.

**Comment by sasbury** [comment]
We are working on a new version of the client that should resolve this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch. Feedback is appreciated.

The new version will allow application code to group subscriptions into dispatchers to control thread usage.

**Comment by sasbury** [comment]
2.0.0 provides a mechanism called dispatchers that allows the application to control thread creation. The client will create ~3 threads + timers for its business (read, write, request/reply handling). The rest is up to the application.
