### ISSUE TITLE
is v0.5.3 or v1.0 is the latest release version?

### ISSUE THREAD

**Issue by huangyigui** [nats-io/java-nats#152]
I am confused which is the latest release version.

v1.0?

or v0.5.3?

**Comment by pappnase99** [comment]
Push for this question. The latest release is listed as v0.5.3 but there seems to be a 1.0 tag.

**Comment by ColinSullivan1** [comment]
1.0 should be the latest.  @mcqueary originally had setup the deployments, perhaps he can comment.

We realize there has not been a release in awhile, have promised one later last year and didn't deliver yet.  We are planning on getting another release put together in the near future.  The NATS team has been extremely busy, but someone will look into this.  Thank you for raising this issue.

**Comment by sasbury** [comment]
We are working on a new version of the client that should resolve this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch. Feedback is appreciated.

**Comment by sasbury** [comment]
version 2.0.0 is released.
