### ISSUE TITLE
How to get queue size?

### ISSUE THREAD

**Issue by ray-verys** [nats-io/java-nats#153]
My understanding is that the java-nats library queues up messages that the server sends and dispatches them to the provided callback consumers as fast as it can. But, there is still a queue that messages can store up in.

How can I get the size of this queue? I need to know how far behind my client is for scaling needs.

Something like:
`int queueSize = nc.getPendingQueueSize();`

**Comment by kozlovic** [comment]
This is available from the subscription object itself. For instance `sub.getPendingMsgs()`. There is also pending bytes, the max that were pending, etc..

**Comment by ray-verys** [comment]
Confirmed this works, thanks for getting back and closing this so quickly @kozlovic
