### ISSUE TITLE
Subscription thread dies silently

### ISSUE THREAD

**Issue by stetra** [nats-io/java-nats#156]
It seems that when a subscription thread dies due to an uncaught exception, there is no stack trace or error output. Is there a way to enable such behavior?

Example program:

    public static void main(String[] args) throws IOException, InterruptedException {
        String subject = "testsubject";

        Connection nc = Nats.connect();
        nc.subscribe(subject, new MessageHandler() {
            @Override
            public void onMessage(Message msg) {
                System.out.println("received message: " + new String(msg.getData()));
                throw new RuntimeException("test exception");
            }
        });

        nc.publish(subject, "test".getBytes());
        Thread.sleep(Long.MAX_VALUE);
    }

When executed, "received message: test" is printed as expected, but there is no error output from the RuntimeException.

**Comment by kozlovic** [comment]
Code in master should catch and ignore any exception thrown from the message callback. Also check https://github.com/nats-io/java-nats/issues/139 for some background info.
