### ISSUE TITLE
Multiple messages received when two connection are subscribed

### ISSUE THREAD

**Issue by rFronteddu** [nats-io/java-nats#157]
So I was doing some tests and I noticed that when I subscribe to a subject with two connection on a NATS that resides in the same machine I get duplicated messages. Is this an expected behavior?

**Comment by rFronteddu** [comment]
I receive 4 messages back not just the two I would expect.
I also did a bunch of tests to try and rule out that was my fault (still it may still be possible). I disabled each connection respectively and verified that I received only one message, then I connected to two different nats and again I received only two messages. Whenever I made them point to the same NATS server I receive 4 messages back.
If you don't have time to test it I will soon make an experiment with a simplified version of my code and I will post a snippet.

**Comment by kozlovic** [comment]
Could you provide a test case please?

**Comment by rFronteddu** [comment]
Yes, I will try and do that tomorrow.

**Comment by rFronteddu** [comment]
I did some more tests and I think it's my fault. Sorry to have wasted your time.

**Comment by rFronteddu** [comment]
I still don't understand why it's happening, I will write something when I do. 
Have a good one.

**Comment by rFronteddu** [comment]
Ah now I understand it is normal that I receive 4 message because I publish into two connections so I will see one message per subscriber times 2. Now I get it.
