### ISSUE TITLE
Establishing connection vs reconnecting.

### ISSUE THREAD

**Issue by Imaskar** [nats-io/java-nats#158]
If you have established NATS connection and some errors occured, you will reconnect in short time. But if error occures when you establishing a connection, it will fail and not try again. But first action doesn't differ much from any later action. So why not treat it as reconnectable?

What current behavior leads to is code redundancy. User needs to check if jnats connected successfully and if not, try again later (and also buffer and later replay all actions). Then jnats itself tries to send a message and if not, tries again later.

Proposed change: immediately unconditionally create connect  in 'disconnected' state and start reconnection cycle.

**Comment by sasbury** [comment]
This feature is available in 2.0.0 using an async connection API.
