### ISSUE TITLE
Release java 1.1

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/java-nats#159]
- [ ] Fix/update broken parts of the deployment process
- [ ] Update sonatype credentials for Synadia users
- [ ] Regenerate certificates
- [ ] Update Travis secrets

NOTE:  I will be extremely busy until after KubeCon/CloudNativeCon but can revisit this in mid-May.

**Comment by igoberman** [comment]
Hi, when do you plan to release the API? we really want to get a fix for https://github.com/nats-io/java-nats/issues/113

**Comment by igoberman** [comment]
Is this project still maintained? There has been no official release for over a year now.

**Comment by sasbury** [comment]
I have started on a major update of the Java client, which will fix #113 as well as other issues. I just joined the team, but this is my top priority and I am working furiously towards it. Hopefully more news in the next couple weeks.

If you have other issues, please get them in asap. And if you have a chance, please complete our brief survey (< 2 mins) and tell us about your experience with NATS. https://goo.gl/forms/DHir9vNBZirNuaFn2

**Comment by igoberman** [comment]
Thanks! I am looking forward to this release. Would be nice to have SNAPSHOT releases published to maven. I had to build 1.1-SNAPSHOT on my machine. 

Also, tests in NUIDTest did not pass with the error below. I had to comment these out to make a successful build.
io.nats.client.NUIDTest
testProperPrefix(io.nats.client.NUIDTest)  Time elapsed: 5.015 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds
	at io.nats.client.NUIDTest.testProperPrefix(NUIDTest.java:88)

**Comment by sasbury** [comment]
The new version is available in the branch version2. It does have some breaking API changes to help us simplify and resolve some API choices.  I am leaving the issue open for now, but if you are interested  please try the new library in the version2 branch. Feedback is appreciated.

**Comment by sasbury** [comment]
2.0.0 is released.
