### ISSUE TITLE
How to get client's internal queue size?

### ISSUE THREAD

**Issue by ray-verys** [nats-io/java-nats#160]
Very similar to my last issue, that question was how to get the size of the queued incoming messages. This is how to get the size of the queue that stores outgoing messages. I believe this queue only grows when all the nats instances the client is connected to go down and cannot be reached.

Here's what I'm doing:

- start a nats server locally
- connect to it using the client
- shutdown the local nats server
- `publish` using the client
- observe that no errors were thrown
- restart the nats server
- observe that all the messages I published come through as soon as the client reconnects

What I've noticed at this point is that the messages that I'm publishing don't fail or get discarded. I know this because 30 seconds later when I restart the local nats server all the messages go through. This tells me that the client has an internal queueing mechanism that is storing the messages and waiting until a new connection is established to send them.

*The Questions*
How do I get the size of that queue? If the nats server goes down I need to know how many messages have been queued up in the client.

Maybe something like: `client.getQueuedPublishedMessages()` lol

Thanks!

**Comment by kozlovic** [comment]
While the client gets disconnected, all published messages and new subscriptions protocols go into a reconnect buffer. Once the library reconnects, this buffer is flushed.
See https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/ConnectionFactory.java#L691

You can't know how many messages are queued. But you could reduce the size to a very low value, then any publish call while the library is disconnected would result to a publish error.

**Comment by ray-verys** [comment]
Appreciate the quick response! We'll have to look into solutions with this information. Thanks again!

**Comment by kozlovic** [comment]
Anytime!
