### ISSUE TITLE
Build Error on Ubuntu

### ISSUE THREAD

**Issue by Brianchat** [nats-io/java-nats#162]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jnats: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/brian/Code/java-nats && /usr/lib/jvm/java-10-oracle/bin/java -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/home/brian/Code/java-nats/target/coverage-reports/jacoco-ut.exec -jar /home/brian/Code/java-nats/target/surefire/surefirebooter14092280226774052527.jar /home/brian/Code/java-nats/target/surefire/surefire8036098857378489951tmp /home/brian/Code/java-nats/target/surefire/surefire_0584513864574697508tmp

**Comment by sasbury** [comment]
We are working on a new version of the client that I hope resolves this issue, I am leaving the issue open for now, but if you are interested in this feature please try the new library in the version2 branch. Feedback is appreciated.

**Comment by sasbury** [comment]
Please try again on 2.0.0, I am marking closed for now.
