### ISSUE TITLE
Event callbacks : get connected url returns null

### ISSUE THREAD

**Issue by materia2021** [nats-io/java-nats#164]
ConnectionFactory cf = new ConnectionFactory();
		cf.setServers(natsServers);
		Connection nc = cf.createConnection();

		nc.setDisconnectedCallback(event -> {
			log.info("Got disconnected from NATS " + event.getConnection().getConnectedUrl());
		});

		// See who we are connected to on reconnect.
		nc.setReconnectedCallback(event -> {
			log.info("Got reconnected to NATS " + event.getConnection().getConnectedUrl());
		});

		// Setup a callback to be notified when the Connection is closed
		nc.setClosedCallback(event -> {
			log.info("Connection has been closed from NATS " + event.getConnection().getConnectedUrl());
		});

whenever the callback gets triggered. the connected url returns null

**Comment by sasbury** [comment]
We are testing a major re-write of the library under the version2 branch. The callback API is a bit different, but this URL is still available so I will make sure the tests check its existence.

I will leave this issue open until we release version2, but feel free to check out the new release and let us know of problems.

**Comment by materia2021** [comment]
thanks! will surely check the new version

**Comment by sasbury** [comment]
Fixed in 2.0.0
