### ISSUE TITLE
JNats 2.x is no longer a bundle

### ISSUE THREAD

**Issue by oscerd** [nats-io/java-nats#166]
In version 0.5 the maven-bundle-plugin support was introduced to make jnats OSGI friendly, is there a specific reason for the removal of it in 2.x?

**Comment by sasbury** [comment]
Oversight during the switch to Gradle I will look into it.

**Comment by sasbury** [comment]
Should be fixed in 2.0.1, if you get a chance to try that branch, or use the SNAPSHOT jar they should be updated in a few minutes.

**Comment by oscerd** [comment]
Thanks for your fast response. I'll test tomorrow. When do you plan 2.0.1 release?

**Comment by sasbury** [comment]
It should be in the snapshot now, but as to the actual release, I am thinking end of the month.

**Comment by oscerd** [comment]
Looks good, thanks! I'll wait for the new release.
