### ISSUE TITLE
Message Ack?

### ISSUE THREAD

**Issue by bobbyhubbard** [nats-io/java-nats#171]
Newbie question. I'm noticing that messages are being redelivered when using the Dispatcher. Is there a way to acknowledge a message so that it is only delivered once?

**Comment by bobbyhubbard** [comment]
Ah reply-to. So without a reply-to, the message publisher may be intending to not support ack for that subject and therefore intends redeliver.  That may be what is happening here. 

Thanks for the quick reply!

**Comment by sasbury** [comment]
yes, if the publisher expects a reply and doesn't get one it could be retrying.

**Comment by bobbyhubbard** [comment]
Yes sorry
________________________________

**Comment by sasbury** [comment]
No worries, thanks for the report, let me know if you have any other issues.
