### ISSUE TITLE
NullPointerException when reconnecting to Nats server.

### ISSUE THREAD

**Issue by igoberman** [nats-io/java-nats#172]
We are getting NullPointerException when connection to the server is broken and Nats API tries to reconnect. We are using the latest version of the API 2.0.2.

java.lang.NullPointerException
io.nats.client.impl.NatsConnection.tryToConnect(NatsConnection.java:298)
io.nats.client.impl.NatsConnection.reconnect(NatsConnection.java:213)
io.nats.client.impl.NatsConnection.closeSocket(NatsConnection.java:445)
io.nats.client.impl.NatsConnection.lambda$handleCommunicationIssue$2(NatsConnection.java:403)
java.lang.Thread.run(Thread.java:748)

Now looking at NatsConnection.java:298, you can see that there is no null check on pongFuture. It returns null.
            Future<Boolean> pongFuture = sendPing();
            pongFuture.get(connectTimeout.toNanos(), TimeUnit.NANOSECONDS);

These are our options for the Nats connection:
				Options natsOptions = new Options.Builder()
						.servers(new String[]{ NATS_URL })
						.maxReconnects(-1)
						.pingInterval(Duration.ofSeconds(1))
						.connectionListener((conn, e) -> {
							logger.info("NATS: connection event - {}", e);
						}).build();

**Comment by sasbury** [comment]
i am guessing there is a timing thing where the pings back up, i don't know a good way to force the error, but I am adding an if !=null check for the pong future and adding a check in the ping timer to not ping if the connection is down. Making sure this doesn't break anything and will check in. Should go out in v2.1.0 next week (bumping the version because we are adding a new API to drain connections.)

**Comment by sasbury** [comment]
If you get a chance can you try out the 2.1 branch? I want to release 2.1 to get this fix and the new Drain API in the master, but I had trouble replicating your issue so wanted you to give it a shot.

**Comment by igoberman** [comment]
I will try it later today.

**Comment by igoberman** [comment]
Is this correct dependency to use? Looks like it is not rebuild - I still get NPE.
			<dependency>
				<groupId>io.nats</groupId>
				<artifactId>jnats</artifactId>
				<version>2.1.0-SNAPSHOT</version>
			</dependency>

**Comment by sasbury** [comment]
ok, i got the maven snapshot to update, sorry about that.

**Comment by igoberman** [comment]
It did not crash. so appears to be fixed. thanks.
