### ISSUE TITLE
Error in Connecting to server

### ISSUE THREAD

**Issue by asbapat** [nats-io/java-nats#182]
I tried creating a nats client on android and connecting to the default server, however I am getting an exception "Unable to connect to the server" while establishing a connection.

**Comment by sasbury** [comment]
Can you connect to the same gnatsd from a desktop app or example? That exception message leads me to think the app can't find the server on the network.

Also, what versions of the library and server are you using?

**Comment by asbapat** [comment]
I have not tried with a desktop application. I tried the same code snippet from "NatsDispatch.java" from the examples. Server is running as a Windows Service on one of the machines in our Lab and the url that I am using from android device to connect to the server is "nats://ip:4222"; where ip is the IP address of the machine on network. 

Is there any error in my approach to connect to the server?

**Comment by sasbury** [comment]
I am just wondering if the android device can't see the server or something. The other possibility is a connection timeout.

The other thing we can do to debug is set up an errorhandler using the options (https://nats.io/documentation/writing_applications/advanced/ has an example). That should tell us about any exceptions in the client or errors from the server.

**Comment by asbapat** [comment]
Thank you for your support, I was able to connect to the server successfully.

**Comment by Gorrgonzola** [comment]
> Thank you for your support, I was able to connect to the server successfully.

Could you please elaborate on how you resolved this issue?

**Comment by codenoid** [comment]
@asbapat how ?

**Comment by darktanker89** [comment]
@asbapat how ?
