### ISSUE TITLE
Compatibility with lower versions of Android

### ISSUE THREAD

**Issue by asbapat** [nats-io/java-nats#184]
Hi,

I tried running the nats client on lower version of Android (API 21) and it threw a "java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;" for the class Options.Builder implemented in the code.

How can I implement this library for running nats client subscription of API Level < 26?

Crash Report:
`2018-10-16 11:21:48.656 14742-14759/com.example.aniketbapat.demoapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.example.aniketbapat.demoapp, PID: 14742
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:318)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)

     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
        at io.nats.client.Options.<clinit>(Options.java:80)
        at io.nats.client.Options$Builder.<init>(Options.java:390)
        at com.example.aniketbapat.demoapp.MainActivity$ConnectServer.doInBackground(MainActivity.java:70)
        at com.example.aniketbapat.demoapp.MainActivity$ConnectServer.doInBackground(MainActivity.java:60)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762)`

**Comment by kkocel** [comment]
Hi, I think it's related with the fact that java-nats project is written in Java 8 and such is supported from version 24 of Android.

**Comment by asbapat** [comment]
Not even API 24. java-nats depends on "java.time.Duration" which was added to Android after API 26. so it does not work with Android version lower that API 26.

Does this mean that there in now way that I can use this library in application running on Android lower than API 26 ?

**Comment by sasbury** [comment]
When I started on the library refactor, which turned into a rewrite, one of the goals was to move the code up to the later versions of Java. Unfortunately this did hurt the Android usage. At the time our thinking was that you could either use the 1.x version of the library on Android, or we would look for feedback and possibly make a special version. (My thinking was that network connectivity vs power were something else mobile specific we should address.)

JDK-wise we are still 3 versions behind the latest (although I think that whole situation is a mess so...)

Are there any other blockers for Android? Maybe we can turn this issue into something we can try to address in a branch, i hate to roll back to Java5 or something.

**Comment by kkocel** [comment]
I would say there are at least three big issues - lambdas, CompletableFuture, Duration. I think that starting `nats-android` would be an option ;)

**Comment by kkocel** [comment]
As @sasbury stated - his original intention was to use latest version of java possible. IHMO keeping `Android` version on separate branch could be a mess, re-architecturing the whole project into `core` part and platform specific components would be also great time investment. I just don't know, I'm just a random github user ;) I would leave that strategic decision to project maintainers.

**Comment by sasbury** [comment]
Agreed that a branch is likely too ugly. But I also hate to see the library get too far behind the latest JDK. Perhaps a new project is in order, that can support not just the right class limitations but also any mobile specific concerns.

**Comment by KORuL** [comment]
Where can i find version for android api <24?

**Comment by KORuL** [comment]
implementation 'io.nats:jnats:1.0' work fine with gnatsd Release v1.3.0 on android > 18
Thanks a lot!
I create Issue for others people #198

**Comment by schmidh** [comment]
Sidenote: Oreo (Api26) has already a market share of 20%. In the first half of 2018 it was only 5%. Marshmallow and Nougat are getting eaten up - bit by bit. In a year's time Oreo will probably have taken the lead.

**Comment by kedzie** [comment]
I am making an effort to make this Android compatible.  I replaced the `java.time.Duration` with an implementation based on `TimeUnit`.  Lambdas are supported on Android with dusugaring.  Only outstanding issue i see is `CompletableFuture`.  How essential is that vs a normal Future?

**Comment by kedzie** [comment]
I some uses of CompletableFuture, in the tests at least, are silly and can be replaced with . a CountDownLatch.

**Comment by sasbury** [comment]
android compatibility is really asking for lower JDK support and I think we should do that in a new repo, I don't think that the main library should be constrained to a version of the JDK that is more than 3 versions behind.

**Comment by kedzie** [comment]
Even with a new repo the approach I would take is cloning this and replacing the CompletableFuture.  That is the only thing standing in the way.  Lambdas are fine.  https://developer.android.com/studio/write/java8-support .

**Comment by kedzie** [comment]
I did the work.  You can decide about the new repo with the PR in front of you.  #211

**Comment by sasbury** [comment]
Closing - we are pointing to the repo now :-)

https://nats.io/download/kedzie/nats-android/
