### ISSUE TITLE
Serializable Options

### ISSUE THREAD

**Issue by laugimethods** [nats-io/java-nats#194]
To be able to use `Options` in distributed environments (like Spark, see https://github.com/Logimethods/nats-connector-spark), the `io.nats.client.Options` Class should be declared as `Serializable`.

Best regards,
Laurent

**Comment by laugimethods** [comment]
Don't know how then some fields will behave, like `SSLContext`,  `AuthHandler`,  `ErrorListener`,  `ConnectionListener`...

**Comment by sasbury** [comment]
You can make the options from properties, although not everything can be in there.

As you say some of the items may not travel, the SSL context has to have access to the files. If you use the default ssl context that might work. Authhandler needs access to the NKey which i would not want to pack up for anyone.

I am thinking properties are the best bet here.

**Comment by laugimethods** [comment]
I'll use Properties for now, which btw is easier for me to implement since I do already propagate a `Properties` object.

However, I would like in the future to be able to serialize (with as much as possible of its properties) a native `Options` object for two reasons:
- It will allow the API of the Spark / NATS to be more similar to the one of this Java Nats library (especially since an `Options` object is now the way to define the parameters of the connection)
- All (Serializable) current and future parameters defined by the Options.Builder interface will be right away availables to my own connector

**Comment by sasbury** [comment]
Closing in favor of properties, I am hesitant to provide a partially serializable object when callbacks are so important.
