### ISSUE TITLE
[question] Request/Reply from many queued subscribers

### ISSUE THREAD

**Issue by mlipovsky** [nats-io/java-nats#212]
Hi,
Is there a way to implement a publisher expecting a reply from all queued subscribers?

example:
SUB_A1 = nc.subscribe("hello", "a", cb=message_handler_a)
SUB_A2 = nc.subscribe("hello", "a", cb=message_handler_a)

SUB_B1 = nc.subscribe("hello", "b", cb=message_handler_b)
SUB_B2 = nc.subscribe("hello", "b", cb=message_handler_b)

response = await nc.request("hello", b'hi', 0.2)
-> response contains response one from SUB_A and one from SUB_B

Thanks

**Comment by sasbury** [comment]
You can do it with a normal publish, but not with ns.request. I have a few examples, here is one where we use a hardcoded reply subject and wait for multiple responses, you should probably use a more random response subject.

https://github.com/ConnectEverything/solvingproblems_java/blob/master/src/main/java/solutions/ex18_search/Search.java
