### ISSUE TITLE
simple request/reply hangs time to time

### ISSUE THREAD

**Issue by eisig** [nats-io/java-nats#213]
Simple request/reply demo. the request side hangs time to time.

demo proejct: https://github.com/eisig/nats-demo1.git
## Deploy env:
 aws amazon linux2: c5d.large。(1 or 3 instances)
## steps
1. `mvn package` the project 
2. start nats server: `./gnatsd-v1.4.1-linux-amd64/gnatsd &`
3. start the reply app:` java -cp nats-demo-1.0-SNAPSHOT.jar  io.eg.nats.demo.NatsReply &`
4. run `java -Djava.security.egd=file:/dev/./urandom -cp nats-demo-1.0-SNAPSHOT.jar  io.eg.nats.demo.NatsReq`

Most of the time the client can not finish 1000 requests. It will hangs.

**Comment by sasbury** [comment]
I re-ran the autobench example to make sure I am able to run R/R. I got pretty good numbers:

**Comment by sasbury** [comment]
Hm, github gui got me. As I was saying, I got pretty good numbers from the autobench:

ReqReply 0b              20,000              8,367 msg/s       0.00 b/s
ReqReply 8b              20,000              8,738 msg/s     68.27 kb/s
ReqReply 32b             10,000              8,570 msg/s    267.84 kb/s
ReqReply 256b            10,000              8,718 msg/s      2.13 mb/s
ReqReply 512b            10,000              8,725 msg/s      4.26 mb/s
ReqReply 1k              10,000              8,684 msg/s      8.48 mb/s
ReqReply 4k              10,000              8,309 msg/s     32.46 mb/s
ReqReply 8k              10,000              7,879 msg/s     61.56 mb/s

which runs over 10k request reply, so I am hoping the issue isn't in the library.

Some thing to try...

* Can you run the server with -DV and look for any errors
* Can you add an error and connection listener to your example, just print out messages.

I have a theory that there could be a slow consumer problem, the DV or connection listener will tell us for sure. The error listener should find any exceptions. If those don't work we will dig a bit deeper.

**Comment by eisig** [comment]
1. I add one line  before executing  the test(before`io.nats.examples.autobench.NatsAutoBench` line 92) to show where hangs.
```
System.out.println("start at: " + (System.currentTimeMillis() / 1000) + ": " + test.getName());
test.execute(connectOptions);
```

2. start the test 
 java -Djava.security.egd=file:/dev/./urandom -cp jnats-2.4.1-SNAPSHOT-examples.jar:jnats-2.4.1-SNAPSHOT.jar   io.nats.examples.autobench.NatsAutoBench small

3. the logs 
```
Connecting to gnatsd at nats://localhost:4222
Running warmup
Current memory usage is 127.34 mb / 235.50 mb / 836.00 mb free/total/max
Executing tests start at: 1551765199: PubOnly 0b
.start at: 1551765200: PubOnly 8b
.start at: 1551765200: PubOnly 32b
.start at: 1551765201: PubOnly 256b
.start at: 1551765202: PubOnly 512b
.start at: 1551765202: PubOnly 1k
.start at: 1551765203: PubOnly 4k
.start at: 1551765203: PubOnly 8k
.start at: 1551765204: PubSub 0b
.start at: 1551765205: PubSub 8b
.start at: 1551765206: PubSub 32b
.start at: 1551765207: PubSub 256b
.start at: 1551765208: PubSub 512b
.start at: 1551765209: PubSub 1k
.start at: 1551765210: PubSub 4k
.start at: 1551765210: PubSub 8k
.start at: 1551765211: PubDispatch 0b
.start at: 1551765212: PubDispatch 8b
.start at: 1551765213: PubDispatch 32b
.start at: 1551765214: PubDispatch 256b
.start at: 1551765215: PubDispatch 512b
.start at: 1551765216: PubDispatch 1k
.start at: 1551765216: PubDispatch 4k
.start at: 1551765217: PubDispatch 8k
.start at: 1551765217: ReqReply 0b
.start at: 1551765219: ReqReply 8b
.start at: 1551765579: ReqReply 32b
.start at: 1551765880: ReqReply 256b
.start at: 1551765881: ReqReply 512b
```
The ReqReply tests take very long time to finish.
the finnal result:
```

ReqReply 0b               1,000              1,262 msg/s       0.00 b/s
ReqReply 8b               1,000                  2 msg/s      22.22 b/s
ReqReply 32b                500                  1 msg/s      53.27 b/s
ReqReply 256b               500              1,200 msg/s    300.09 kb/s
ReqReply 512b               500                  1 msg/s     710.61 b/s
ReqReply 1k                 500              1,237 msg/s      1.21 mb/s
ReqReply 4k                 500              1,316 msg/s      5.14 mb/s
ReqReply 8k                 500              1,183 msg/s      9.25 mb/s
````

3. The problem does not appear in my mac os machine.
when hangs almost every time when run in amazon ec2(c5d.large, os: amazon linux2) ;
when change install type to c5d.xlarge, it only hangs sometimes.

**Comment by eisig** [comment]
1. The nats server log(with -D)
....
[26259] 2019/03/05 06:04:41.582570 [DBG] 127.0.0.1:54356 - cid:164 - Client connection created
[26259] 2019/03/05 06:06:41.579583 [DBG] 127.0.0.1:54354 - cid:163 - Client Ping Timer
[26259] 2019/03/05 06:06:41.579623 [DBG] 127.0.0.1:54354 - cid:163 - Delaying PING due to activity 2m0s ago
[26259] 2019/03/05 06:06:41.582820 [DBG] 127.0.0.1:54356 - cid:164 - Client Ping Timer
[26259] 2019/03/05 06:06:41.582849 [DBG] 127.0.0.1:54356 - cid:164 - Delaying PING due to activity 2m0s ago
[26259] 2019/03/05 06:08:41.579903 [DBG] 127.0.0.1:54354 - cid:163 - Client Ping Timer
[26259] 2019/03/05 06:08:41.583092 [DBG] 127.0.0.1:54356 - cid:164 - Client Ping Timer
[26259] 2019/03/05 06:10:41.580271 [DBG] 127.0.0.1:54354 - cid:163 - Client Ping Timer
[26259] 2019/03/05 06:10:41.580322 [DBG] 127.0.0.1:54354 - cid:163 - Delaying PING due to activity 1m0s ago
[26259] 2019/03/05 06:10:41.583307 [DBG] 127.0.0.1:54356 - cid:164 - Client Ping Timer
[26259] 2019/03/05 06:10:41.583323 [DBG] 127.0.0.1:54356 - cid:164 - Delaying PING due to activity 1m0s ago
[26259] 2019/03/05 06:10:41.839670 [DBG] 127.0.0.1:54356 - cid:164 - Client connection closed
[26259] 2019/03/05 06:10:41.879822 [DBG] 127.0.0.1:54354 - cid:163 - Client connection closed

**Comment by sasbury** [comment]
Those performance numbers are pretty horrible. I wonder if it is something about hte networking on that machine. What happens if you run your program locally?

As another test what happens if you put a sleep in the request program, maybe just send 100/sec or something like that.

**Comment by eisig** [comment]
It work fine on my local env. 
I have try to recreate  several new ec2 using  the official image, without install anything except the openjdk. It situation remain the same.
If I put a sleep(10ms) in the reply or request program, It work fine. 
If I change the os image to ubuntu, It work fine.

**Comment by sasbury** [comment]
Hm, I am not sure what we can do with the library. It seems like a networking/OS - maybe JDK - issue. Thoughts on resolving? My first thought is just to close the issue, but I want to make sure we capture the problem for others.

**Comment by eisig** [comment]
I would close this issue now. If I have time to figure out what is wrong,I will leave a comment here.

**Comment by sasbury** [comment]
Sounds good, thanks for digging in, i am sorry we didn't discover the root issue.
