### ISSUE TITLE
Thread pools

### ISSUE THREAD

**Issue by kedzie** [nats-io/java-nats#214]
Threads are instantiated all over the code.  I suggest using an ExecutorService passed in through Options which will be stored in NatsConnection and used by NatsDispatcher/NatsSubscription/etc.. 

By default it can use a thread pool.

**Comment by sasbury** [comment]
Fixed with 776f1349b08fa964917a3cf5d1b0de0ee0bc1fd8

**Comment by sasbury** [comment]
Released this fix, missed it in the commit.
