### ISSUE TITLE
Race condition can prevent message from being read until another message is received

### ISSUE THREAD

**Issue by brianshannan-wf** [nats-io/java-nats#220]
I'm not sure if anyone here is very familiar with the java client, but I was doing some debugging of an intermittent issue and I think tracked it down, but I'm not sure the best way to fix it. What I think is happening is
1. thread1 - https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/impl/MessageQueue.java#L136 is called, and no messages are available in the queue.
2. thread2 - https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/impl/MessageQueue.java#L101 is called. A message is received, but no waiters are currently in the queue, so nothing is signaled.
3. thread1 - Our waiter is eventually added, and https://github.com/nats-io/java-nats/blob/master/src/main/java/io/nats/client/impl/MessageQueue.java#L154 is called as our waiter wasn't in the list when the message was received, so we weren't able to be notified and our thread is parked, and our subscriber never receives a message. The message is pulled off the queue when another message arrives to notify the waiter, but sometimes that doesn't occur for several seconds, leaving our client receiving a timeout for the first message

I can reproduce the issue with this patch and the `testPopBeforeTimeout` test. The best case scenario would be the message is received as soon as the sleep in `waitForTimeout` is over, instead the test spins for a long, long time. (Sorry for the line endings)
```
diff --git a/src/main/java/io/nats/client/impl/MessageQueue.java b/src/main/java/io/nats/client/impl/MessageQueue.java
index 95e8fce..100bb6a 100644
--- a/src/main/java/io/nats/client/impl/MessageQueue.java
+++ b/src/main/java/io/nats/client/impl/MessageQueue.java
@@ -149,6 +149,8 @@ class MessageQueue {
                     }
                 }

+                Thread.sleep(5000);^M
+^M
                 waiters.add(t);
                 if (timeoutNanos == 0) {
                     LockSupport.park();
@@ -294,4 +296,4 @@ class MessageQueue {

         this.queue.addAll(newQueue);
     }
-}
\ No newline at end of file
+}^M
diff --git a/src/test/java/io/nats/client/impl/MessageQueueTests.java b/src/test/java/io/nats/client/impl/MessageQueueTests.java
index eadd84a..07aeeb4 100644
--- a/src/test/java/io/nats/client/impl/MessageQueueTests.java
+++ b/src/test/java/io/nats/client/impl/MessageQueueTests.java
@@ -109,7 +109,7 @@ public class MessageQueueTests {
         t.start();

         // Thread timing, so could be flaky
-        NatsMessage msg = q.pop(Duration.ofMillis(200));
+        NatsMessage msg = q.pop(Duration.ofMillis(2000000));^M
         assertNotNull(msg);
     }

@@ -519,4 +519,4 @@ public class MessageQueueTests {
         q.filter((msg) -> {return true;});
         assertFalse(true);
     }
-}
\ No newline at end of file
+}^M
```

**Comment by sasbury** [comment]
Just to confirm - this was a rare - super annoying - hard to find issue? I am trying to think of a way to reproduce without editing the message queue and it looks super sneaky and annoying. Hats off for finding it.

What is the NATS pub/sub/msg level of how this is happening?

**Comment by brianshannan-wf** [comment]
It happens most often in our tests, as they can be fairly single threaded and request/response oriented, so this happening once fails them. There are a fairly large number of tests so the odds of at least one failing is relatively high.

The client sends a message to nats, nats sends a message to a subscriber. Then quite awhile later the subscriber sends a message back to nats, and nats sends that message to the client. Something like
