### ISSUE TITLE
High latency on Windows

### ISSUE THREAD

**Issue by AnatolyKap** [nats-io/java-nats#224]
When I run NATS server on Linux and io.nats.examples.autobench.NatsAutoBench on Windows I see huge latency >30 milliseconds
If I switch roles of the same machines (run NATS server on Windows and NatsAutoBench on Linux)  - then latency <0.4 millisecond

**Comment by sasbury** [comment]
The asymmetry makes me think the issue isn't in the library. Do repeated runs on linux show any sort of issue?

I will try to give windows a shot next week, but if it is just windows + JVM i may not be able to do anything.

**Comment by AnatolyKap** [comment]
I have repeated this experiments several times on several machines. Results are consistent:
- Windows => Linux - BAD
- Linux => Windows - GOOD
- Windows => Windows - BAD
- Linux => Linux - GOOD

In all cases having java-nats on Windows leads to high latency.

**Comment by AnatolyKap** [comment]
I don't think this is a problem of  Windows as such. There are a lot of java applications which works on Windows just fine (including one we developed)

**Comment by sasbury** [comment]
I will try to profile on windows and see if something jump outs.

**Comment by sasbury** [comment]
worked with a co-worker that has bootcamp on a mac, we can see that the latency and req-rep tests have much worse numbers than pub or pub/sub. I will try to look into it, although if you have a profiler it would be interesting to hear what numbers you see. The big question is are the benchmarks not working right or is it the underlying library. At least part of the library is fine if pub/sub is ok, so that makes me wonder if this is in the benchmark code.

Have you seen problems with other apps, or just the autobench?

**Comment by AnatolyKap** [comment]
I saw a problem in my app at first and that's why I looked at benchmark

**Comment by sasbury** [comment]
only latency, or do you see throughput issues on your app?

**Comment by AnatolyKap** [comment]
Only latency

**Comment by AnatolyKap** [comment]
Hi 
How are things going?

**Comment by sasbury** [comment]
haven't had a chance to set up a dev environment. If you get a chance to do any profiling and can find the hotspot I can take a look, otherwise I need to find some time to get a profiler on a windows box.

**Comment by AnatolyKap** [comment]
I wrote very simple test which use pure java Socket. I run it on the same Windows machines and got 0.2ms latency
So it's not OS / network / hardware problem

**Comment by sasbury** [comment]
i wonder if it is the way i use locksupport on windows? I will try to take a look next week, wrapped up in something else at the moment.

**Comment by AnatolyKap** [comment]
As soon as you use pure java it should work on any OS (theoretically)

**Comment by sasbury** [comment]
and yet, the library is pure java and we have a latency issue :-)

**Comment by sasbury** [comment]
can you shoot me your test app, i tried profiling the library and all the time is spent in the socket. There aren't a lot of settings to play with so i am curious how your test looks on my machine

**Comment by sasbury** [comment]
Also, what version of java are you using, and out of curiosity is this a windows box or a vm?

**Comment by ColinSullivan1** [comment]
@AnatolyKap , Do other apps have this issue?  E.g., if you ping your linux box from windows a number of times, do you see latency spikes?  e.g. `ping -n 40 <linux box ip>`

**Comment by AnatolyKap** [comment]
Hi 
This is test I used
[TcpLatency.txt](https://github.com/nats-io/java-nats/files/3145295/TcpLatency.txt)

**Comment by AnatolyKap** [comment]
@sasbury 
I've reproduced the problem in several machines. 
For example at two AWS VM boxes r3.8xlarge with Windows Server 2012R2, java version "1.8.0_101"

@ColinSullivan1 
Other application works fine on the same VMs. It uses oracle database at 1-st VM and application server at another. Performance is good, latency is low
I can't run ping at this VMs because ICMP is prohibited there

**Comment by sasbury** [comment]
Digging in, thanks for the TCPLatency test, i am seeing lower numbers there, so trying to figure out whats up. The socket settings don't seem to matter (if you get a chance to comment those out let me know if you see basically the same numbers). I will try to profile again and see if I can find what is going on.

**Comment by sasbury** [comment]
Digging around I noticed something I wanted note here, the message queue is slower to "push" on windows:

Windows (virtual box)
Total time to perform 10,000,000 push operations was 1,302 ms, 130.28 ns/op
        or 7,675,782.913 op/s

Mac (same machine)
Total time to perform 10,000,000 push operations was 306 ms, 30.604 ns/op
	or 32,675,706.209 op/s

Non-push metrics aren't seeing the same difference. Will dig more.

**Comment by sasbury** [comment]
@AnatolyKap can you paste your numbers from the latency test in NatsAutoBench when you have some time. I am curious if they line up with mine.

**Comment by sasbury** [comment]
I think i got it - the issue appears to be the spin lock on the message queue - i am now getting numbers from auto bench that match the test app. Will check in shortly in 2.4.4 branch.

**Comment by sasbury** [comment]
With the fix, my numbers on windows virtual box are half of the mac os natively. Latency is comparable to the raw test, especially given the extra work on the NATS side going through the server.

**Comment by AnatolyKap** [comment]
Great news!
Thanks

**Comment by AnatolyKap** [comment]
I've tested the fix - work great!
Thanks again

PS. You haven't yet merged the fix to master branch?

**Comment by sasbury** [comment]
I am hoping to fix 1-2 more issues and do a release at the end of the week.
