### ISSUE TITLE
Nats Bridge

### ISSUE THREAD

**Issue by zackws** [nats-io/java-nats#232]
Could you please help me to do a bridge from activemq to NATS using apache Camel ?
Thank you

**Comment by sasbury** [comment]
what specifically are you asking for help with?

**Comment by sasbury** [comment]
Looks like this already exists ... https://camel.apache.org/nats.html

**Comment by zackws** [comment]
Hello, i want to build a bridge from a jms Queue (activeMq) to nats (Queue) using apache Camel. i'dont know how to code that, I ve already seen the example on github and i couldnt do much about it.
Could you please help me ? 
 Thanks
