### ISSUE TITLE
ConnectionFactory's JavaDoc: provide the list of keys that can be used on the properties.

### ISSUE THREAD

**Issue by laugimethods** [nats-io/java-nats#25]
The connectionFactory is defined by a Properties object, which should be fill with values defined by a defined set of Keys. 
Those keys can be inferred from the actual source code [ConnectionFactory.java](https://github.com/nats-io/jnats/blob/master/src/main/java/io/nats/client/ConnectionFactory.java), but are not listed on the generated [ConnectionFactory API](http://nats-io.github.io/jnats/io/nats/client/ConnectionFactory.html)...

**Comment by mcqueary** [comment]
Isn't this what you're looking for (hint: go to javadoc for `io.nats.client.Constants` and in any property, click `Constant Field Values`? 
http://static.javadoc.io/io.nats/jnats/0.5.3/constant-values.html#io.nats.client.Constants.PROP_CLOSED_CB

**Comment by sasbury** [comment]
ConnectionFactory was removed, but the Options properties are all javadoc'd in version 2.0
