### ISSUE TITLE
Scatter gather pattern support

### ISSUE THREAD

**Issue by Hronom** [nats-io/java-nats#93]
What need to be done:
1. Create reply topic and subscribe
2. Send query on broadcast topic with reply address
3. Listen for responses and unsubscribe after a time limit
4. Aggregate response and return result

Thanks to the @mhaan from Slack, it looks like there is not much changes need to be done to support this feature.

**Comment by sasbury** [comment]
Closing for 1.x, but open to a new PR for 2.x or possibly a doc example for nats.io.
